Console.Write("Введите a: ");
double a = double.Parse(Console.ReadLine());
Console.Write("Введите b: ");
double b = double.Parse(Console.ReadLine());
Console.Write("Введите c: ");
double c = double.Parse(Console.ReadLine());
Console.Write("Введите d: ");
double d = double.Parse(Console.ReadLine());
Console.WriteLine(a+b+c+d);
Console.WriteLine(a*b*c*d);